---
name: 'Core'
about: 'Pull request for core service'
title: '[BE] '
labels: 'BE'
---

[ ] The description of this Pull Request was not generated by AI/agents. All PR submitters are required to manually fill in the Pull Request description.

## Changes Description

<!-- Enter the description of your changes here. -->

## Related Issues

<!-- If this PR is related to any issues, please paste the URLs of the corresponding issues. -->

## Checklist

<!-- Please complete the checklist below and check any boxes that apply to this PR. -->

* [ ] The changes submitted in this Pull Request involve the participation of AI/Agents ()
  * [ ] This Pull Request was completely generated by AI/Agents
  * [ ] A human has manually reviewed the changes generated by AI/Agents and fully understands the relevant modifications and their side effects, 
