FROM alpine
LABEL MAINTAINER="https://github.com/Ghost-chu/PeerBanHelper"
WORKDIR /app
COPY ./docker-entrypoint-native.sh /app/docker-entrypoint.sh
COPY ./target/peerbanhelper-binary /app/
# environment
RUN apk add --no-cache gcompat && \
    wget https://github.com/xerial/sqlite-jdbc/raw/master/src/main/resources/org/sqlite/native/Linux-Musl/x86_64/libsqlitejdbc.so -O /usr/lib/libsqlitejdbc.so && \
    chmod +x /app/docker-entrypoint.sh && \
    chmod +x /app/peerbanhelper-binary

ENTRYPOINT ["/app/docker-entrypoint.sh"]