FROM eclipse-temurin:21-jre-alpine
LABEL MAINTAINER="https://github.com/PBH-BTN/PeerBanHelper"
COPY target/PeerBanHelper.jar /app/PeerBanHelper.jar
USER 0
ENV TZ=UTC
WORKDIR /app
VOLUME /tmp
ENV PATH "${JAVA_HOME}/bin:${PATH}"
ENTRYPOINT ["java","-Xmx256M","-XX:+UseG1GC", "-XX:+UseStringDeduplication","-XX:+ShrinkHeapInSteps","-jar","PeerBanHelper.jar"]