name: "任何其它 - Other"
description: "报告其它分类均无关的问题"

title: "[Other] "
labels:
  - "Other"
body:
  - type: "textarea"
    attributes:
      label: "问题描述 - Issue Description"
      description: |-
        Describe the problem you encounted.
        在此详细的描述你所遇到的问题
    validations:
      required: true
  - type: "textarea"
    attributes:
      label: "额外信息 - Addition Information"
      description: |-
        If you have any related informations, please insert them into this text area.
        如果你还有其他觉得可能对排查和解决此问题有帮助的更多信息，可以在这里告诉我们
      placeholder: "在此填写可能有用的额外信息..."
  - type: checkboxes
    id: check-list
    attributes:
      label: 检查清单 - Check list
      description: |-
        Check and tick checkboxes that listed below
        检查并勾选所有需要勾选的框框
      options:
        - label: "这不是一个错误 （BUG） (This is not an bug/error)"
          required: false
        - label: "PeerBanHelper 已更新到最新版本，非最新版本不接受任何错误反馈，任何非最新版本的 Issue 将被 立 刻 关 闭，不会有人给您提供任何支持 (I'm running the latest version of PBH that can be found in Github Relases, non-latest release won't receive any support)"
          required: false
        - label: "我已检查过 [PBH 文档](https://docs.pbh-btn.com/)（特别是常见问题），且即使使用了搜索也没有找到与此有关的内容 (This not a question/or the question that not listed in README's FAQ or [PBH WIKI](https://docs.pbh-btn.com/))"
          required: false
        - label: "我同意遵守 PBH-BTN 包容性条约，不发布 “嘲讽、骂战、引战、开盒（有时也称为人肉搜索）、人身攻击、仇恨、暴力、侮辱性言辞、违法违规内容、黑灰产活动、危害国家安全的行为、实施或帮助他人实施电信犯罪” 等内容。并已知晓如果仍旧发布这些内容，我的账号将立即从包括但不限于 PBH-BTN 组织、社交软件中被封禁。所有主题、内容都将被立即删除或折叠，撤销、删除我所做出的一切贡献，并封禁我在 BTN 网络中的账号权限，排除我所提交的所有数据。在我违反相关规则时，PBH-BTN 将会把我的注册、登录和最近访问的 IP 地址、电子邮件地址，以及其它可能追踪我或将我去匿名化的信息从定期删除转为永不删除，并在任何国家或地区的政府、公安机关或有关部门需要时无通知地提供这些数据。（I agree to abide by the PBH-BTN Inclusivity Pact by not posting content such as "taunting, name-calling, inciting conflict, doxing (sometimes referred to as human flesh searching), personal attacks, hatred, violence, insulting language, illegal activities, gray and black market activities, actions that endanger national security, and committing or assisting others in committing telecommunications crimes." I am aware that if I continue to post such content, my account will be immediately banned from organizations, including but not limited to PBH-BTN, and social media platforms. All topics and content will be promptly deleted or collapsed, and all contributions made by me will be revoked, deleted, and retracted. Additionally, I will be banned from the BTN network, and all data I have submitted will be excluded. In the event of a violation of these rules, PBH-BTN will change the deletion policy of my registration, login, and most recent IP address, email address, and any other information that may be used to track me or deanonymize me from regular deletion to never deletion, and will provide these data to governments, public security agencies, or other relevant authorities without notice if they request it, regardless of the country or region.）"
          required: false
