name: "错误报告 - Bug Report"
description: "报告与 PeerBanHelper 有关的程序错误 - Report the errors that related to PeerBanHelper"

title: "[BUG] "
labels:
  - "Bug"
body:
  - type: "markdown"
    attributes:
      value: |-
        ## 请注意 - Caution
        This form only used for bug report, for any other cases, please [click here](https://github.com/PBH-BTN/PeerBanHelper/issues/new)  
        此表单**仅用于反馈错误**，如果是其它类型的反馈，请[点击这里以重新选择](https://github.com/PBH-BTN/PeerBanHelper/issues/new/choose)。 
        请尽可能完整且详细地填写所有表单项，以便我们以最高效率并准确的排查故障和诊断问题。
        **错误填写或者没有仔细检查末尾的检查清单，将导致此 Issue 被立刻关闭。**
        **只有最新版本的 PeerBanHelper 才会得到支持，任何非最新版本的 Issue 将被 立 刻 关 闭，不会有人给您提供任何支持** [在此查看最新版本的版本号](https://github.com/PBH-BTN/PeerBanHelper/releases/latest)
  - type: "input"
    attributes:
      label: "版本号 - Version"
      description: |-
        Enter the PBH version that display on WebUI footer or GUI window title.  
        输入您正在使用 PeerBanHelper 的版本号，通常可在窗口标题或者 WebUI 页面的底部找到
      placeholder: "vX.X.X"
    validations:
      required: true
  - type: "textarea"
    attributes:
      label: "操作系统平台和系统架构 - OS  and CPU Arch"
      description: |-
        Enter the OS version/arch that PBH running on (not downloader), E.g Windows, Debian, iStoreOS.
        输入 PBH 所在的操作系统平台（不是下载器），例如：Windows、Debian、iStoreOS 等  
        And please also enter the system arch if you know it, E.g x86, arm64
        此外，您还需要输入系统架构。如果是 x86 设备，则通常为 x64；如果是 arm 设备，则通常为 arm64。请根据实际情况填写。如果不知道，也可以不写系统架构类型。
      placeholder: "操作系统平台名称……"
    validations:
      required: true
  - type: checkboxes
    id: deploy-methods
    attributes:
      label: "部署方式 - Deploy methods"
      description: |-
        Check and tick checkboxes that deploy methods that you're using
        请检查并勾选你正在使用的 PeerBanHelper 部署方式
      options:
        - label: "Windows .exe 安装程序 (Windows .exe Installer)"
          required: false
        - label: "Windows .zip 绿色部署包 (Windows .zip Portable)"
          required: false
        - label: "Docker"
          required: false
        - label: "JAR 包直接启动 (Start via .JAR directly)"
          required: false
        - label: "群晖 DSM 套件 (Synology .spk package)"
          required: false
        - label: "Debian 软件包 (Debian .deb package)"
          required: false
        - label: "RedHat/Fedora 软件包 (RedHat/Fedora .rpm package)"
          required: false
  - type: checkboxes
    id: downloaders
    attributes:
      label: "添加的下载器 - Added Downloaders"
      description: |-
        Check and tick checkboxes if you added those downloader(s) into your PeerBanHelper installation
        请勾选被你添加到 PeerBanHelper 中的下载器类型
      options:
        - label: "qBittorrent"
          required: false
        - label: "BiglyBT/Azureus/Vuze"
          required: false
        - label: "Deluge"
          required: false
        - label: "Transmission"
          required: false
        - label: "BitComet"
          required: false
    validations:
      required: true
  - type: "textarea"
    attributes:
      label: "问题描述 - Issue Description"
      description: |-
        Describe the problem you encounted.
        在此详细的描述你所遇到的问题
    validations:
      required: true
  - type: "textarea"
    attributes:
      label: "复现步骤 - Reproduce steps"
      description: |-
        If you know how to reproduce the error, please type it in this text area.  
        如果你清楚如何复现此故障，也欢迎告诉我们，帮助我们更快的复现它。如果它是一个偶尔才会出现的错误，请告诉我们它通常可能会在什么情况下出现。
      placeholder: |-
        1. 第一步
        2. ...
        3. 出现 BUG!
    validations:
      required: true
  - type: "textarea"
    attributes:
      label: "截图/日志文件 - Screenshot / Logs "
      description: |-
        If you have some screenshot or logs file can help us, please upload them here.  
        如果你有一些截图或者日志能够更好的解释你所提出的问题，你可以在这里上传。
      placeholder: "<截图文件>"
    validations:
      required: false
  - type: "textarea"
    attributes:
      label: "额外信息 - Addition Information"
      description: |-
        If you have any related informations, please insert them into this text area.
        如果你还有其他觉得可能对排查和解决此问题有帮助的更多信息，可以在这里告诉我们
      placeholder: "在此填写可能有用的额外信息..."
  - type: checkboxes
    id: check-list
    attributes:
      label: 检查清单 - Check list
      description: |-
        Check and tick checkboxes that listed below
        检查并勾选所有需要勾选的框框
      options:
        - label: "PeerBanHelper 已更新到最新版本，非最新版本不接受任何错误反馈，任何非最新版本的 Issue 将被 立 刻 关 闭，不会有人给您提供任何支持 (I'm running the latest version of PBH that can be found in Github Relases, non-latest release won't receive any support)"
          required: false
        - label: "所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))"
          required: false
        - label: "我已检查过 [PBH 文档](https://docs.pbh-btn.com/)（特别是常见问题），且即使使用了搜索也没有找到与此有关的内容 (This not a question/or the question that not listed in README's FAQ or [PBH WIKI](https://docs.pbh-btn.com/))"
          required: false
        - label: "我没有检查这个检查清单，只是闭眼选中了所有的复选框，请关闭这个 Issue (I have not read these checkboxes and therefore I just ticked them all, Please close this issue)"
          required: false
        - label: "这不是一个安全漏洞，它可以被安全的公开报告。若需要报告安全漏洞，请[在此报告](https://github.com/PBH-BTN/PeerBanHelper/security/advisories/new) (This not a security related issue, can be safe report in public. If you want report a security exploit, please report it [here](https://github.com/PBH-BTN/PeerBanHelper/security/advisories/new))"
          required: false
        - label: "我同意遵守 PBH-BTN 包容性条约，不发布 “嘲讽、骂战、引战、开盒（有时也称为人肉搜索）、人身攻击、仇恨、暴力、侮辱性言辞、违法违规内容、黑灰产活动、危害国家安全的行为、实施或帮助他人实施电信犯罪” 等内容。并已知晓如果仍旧发布这些内容，我的账号将立即从包括但不限于 PBH-BTN 组织、社交软件中被封禁。所有主题、内容都将被立即删除或折叠，撤销、删除我所做出的一切贡献，并封禁我在 BTN 网络中的账号权限，排除我所提交的所有数据。在我违反相关规则时，PBH-BTN 将会把我的注册、登录和最近访问的 IP 地址、电子邮件地址，以及其它可能追踪我或将我去匿名化的信息从定期删除转为永不删除，并在任何国家或地区的政府、公安机关或有关部门需要时无通知地提供这些数据。（I agree to abide by the PBH-BTN Inclusivity Pact by not posting content such as "taunting, name-calling, inciting conflict, doxing (sometimes referred to as human flesh searching), personal attacks, hatred, violence, insulting language, illegal activities, gray and black market activities, actions that endanger national security, and committing or assisting others in committing telecommunications crimes." I am aware that if I continue to post such content, my account will be immediately banned from organizations, including but not limited to PBH-BTN, and social media platforms. All topics and content will be promptly deleted or collapsed, and all contributions made by me will be revoked, deleted, and retracted. Additionally, I will be banned from the BTN network, and all data I have submitted will be excluded. In the event of a violation of these rules, PBH-BTN will change the deletion policy of my registration, login, and most recent IP address, email address, and any other information that may be used to track me or deanonymize me from regular deletion to never deletion, and will provide these data to governments, public security agencies, or other relevant authorities without notice if they request it, regardless of the country or region.）"
          required: false
