name: DEB Package Build

on:
  workflow_call:
jobs:
  dpkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - id: java_info
        uses: YunaBraska/java-info-action@main
      - uses: actions/download-artifact@v6
        with:
          name: maven-dist
          path: target/
      - name: Build Deb package
        id: build-deb
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
          sed -i "s/<version>/${{ env.PBH_VERSION }}/g" pkg/deb/DEBIAN/control
          mkdir -p pkg/deb/usr/lib/peerbanhelper
          mv target/libraries pkg/deb/usr/lib/peerbanhelper/
          cp target/PeerBanHelper.jar pkg/deb/usr/lib/peerbanhelper/
          cd pkg && dpkg -b deb peerbanhelper_${{ env.PBH_VERSION }}_all.deb
        # 上面那个文件名需要符合收集条件
        env:
          PBH_VERSION: ${{ steps.java_info.outputs.project_version }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: deb-dist
          path: |
            pkg/*.deb
