# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI (push)

on:
  push:
  workflow_dispatch:
jobs:
  Build_Executable:
    name: Build JAR Files
    uses: ./.github/workflows/build_gradle.yml
    secrets: inherit
  Build_Installers:
    name: Generate Installers
    needs: Build_Executable
    uses: ./.github/workflows/build_installers.yml
    secrets: inherit
  Build_Portable:
    name: Generate Portable Version
    needs: Build_Installers
    uses: ./.github/workflows/build_portable.yml
  Build_SPK:
    name: Generate Synology Package
    needs: Build_Executable
    uses: ./.github/workflows/build_spk.yml
    with:
      image: ghostchu/peerbanhelper-snapshot:sha-${{ github.sha }}
  Build_DEB:
    name: Generate Debian Package
    needs: Build_Executable
    uses: ./.github/workflows/build_deb.yml
  Build_PKG:
    name: Generate FreeBSD Package
    needs: Build_Executable
    uses: ./.github/workflows/build_pkg.yml
  Create_Torrent:
    name: Create Torrent
    needs: [ Build_Executable, Build_Installers, Build_SPK, Build_DEB, Build_PKG, Build_Portable ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - id: java_info
        uses: YunaBraska/java-info-action@main
      - name: Determine version
        id: set_version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            SHORT_SHA=$(git rev-parse --short "${{ github.sha }}")
            echo "version=sha-$SHORT_SHA" >> $GITHUB_OUTPUT
          fi
      - uses: actions/download-artifact@v8
        with:
          pattern: PeerBanHelper*
          merge-multiple: true
          skip-decompress: true
          path: "${{ steps.set_version.outputs.version }}"
      - uses: actions/download-artifact@v8
        with:
          pattern: peerbanhelper*
          merge-multiple: true
          skip-decompress: true
          path: "${{ steps.set_version.outputs.version }}"
      - name: Install torrenttools
        run: |
          echo "2d15f8ab3cee5ebb392e3fb219b186cc99efc7224b08b39d298c54e894401a18 torrenttools" > torrenttools.sha256
          wget https://github.com/fbdtemme/torrenttools/releases/download/v0.6.2/torrenttools-0.6.2-linux-x86_64.AppImage -O torrenttools
          sha256sum -c torrenttools.sha256
          chmod +x torrenttools
      - name: Make torrent
        run: |
          APPIMAGE_EXTRACT_AND_RUN=1 ./torrenttools create --simple-progress \
          -t 8 \
          -v hybrid \
          -a udp://tracker.opentrackr.org:1337/announce \
             udp://tracker.publicbt.com:80/announce \
             udp://tracker.openbittorrent.com:80/announce \
             https://sparkle.ghostchu-services.top/announce \
             udp://opentracker.io:6969/announce \
             wss://tracker.openwebtorrent.com:443/announce \
          -c "PeerBanHelper/${{ github.ref }} (${{ github.sha }}) on ${{ github.repository }}. Published by ${{ github.repository_owner }}." \
          -w "https://github.com/${{ github.repository }}/releases/download/" \
             "https://gh-proxy.org/https://github.com/${{ github.repository }}/releases/download/" \
             "https://v4.gh-proxy.org/https://github.com/${{ github.repository }}/releases/download/" \
             "https://v6.gh-proxy.org/https://github.com/${{ github.repository }}/releases/download/" \
             "https://cdn.gh-proxy.org/https://github.com/${{ github.repository }}/releases/download/" \
          -o peerbanhelper.torrent \
          "${{ steps.set_version.outputs.version }}"
      - uses: actions/upload-artifact@v7
        with:
          archive: false
          if-no-files-found: error
          path: peerbanhelper.torrent
  Build_Docker:
    name: Build and Push Docker Images
    needs: Build_Executable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/download-artifact@v8
      with:
        name: gradle-dist
        path: build
    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v4
    - name: Set Up Buildx
      uses: docker/setup-buildx-action@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v6.2.0
      with:
        images: ghostchu/peerbanhelper-snapshot
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,ci-jvm-universal
          type=raw,ci
          type=sha
    - name: Build and push Docker image
      uses: docker/build-push-action@v7.3.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: |
          linux/amd64
          linux/arm64/v8
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}-jvm-universal
        cache-from: type=gha
        cache-to: type=gha,mode=min

  Build_Docker_Standalone:
    name: Build Standalone Docker Images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v4
    - name: Set Up Buildx
      uses: docker/setup-buildx-action@v4
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v6.2.0
      with:
        images: ghostchu/peerbanhelper-snapshot
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,ci-jvm-universal
          type=raw,ci
          type=sha
    - name: Build and push Docker image
      uses: docker/build-push-action@v7.3.0
      with:
        context: .
        file: ./Dockerfile
        push: false
        build-args: |
          GIT_HASH=${{ github.sha }}
        platforms: |
          linux/amd64
          linux/arm64/v8
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}-jvm-universal
        cache-from: type=gha
        cache-to: type=gha,mode=min
